### PR TITLE
Bugfix #36

### PR DESCRIPTION
**Pull request by rpitingolo**
@ptatian can you please review? You will need to update your config file to point to the new autoexec.sas to test.

### CODE REVIEW

**Comment by ptatian** [comment]
Thanks, @rpitingolo. This seems to work fine. The challenge is that we need to make sure everyone can edit their config files before we roll this out, because otherwise it will break their SAS. Alternatively, the Stdhead code could be written so that it tests whether _dcdata_l_drive and _dcdata_r_drive are assigned values already and, if not, assigns the value of D. That way, people who have the current set up don't need to change anything. Perhaps we should try that.

**Comment by rpitingolo** [comment]
@ptatian that sounds like a good approach. I'll work on updating the code to make that work.

**Comment by rpitingolo** [comment]
@ptatian This is ready for your review again. If autoexec isn't used then the drive letters will default to D and L as before. Since most of us are already using those letters, we can just roll this out for situations where people need to use alternative drive letters.

**Comment by rpitingolo** [comment]
@ptatian sure. I'll work with Will to get this implemented for him.

**Pull request merged**
